### ISSUE TITLE
lets-chat_with_a_friend.ipynb

### ISSUE THREAD

**Issue by tae898** [leolani/cltl-chatbots#10]
![image](https://user-images.githubusercontent.com/10544311/159989600-87abec3b-4653-4e00-b0d2-01dac802c2a5.png)

**Comment by piekvossen** [comment]
Notebooks do not work due to many api changes. This will be fixed later. For now use the scripts in bots

**Comment by piekvossen** [comment]
“src.” is removed from import of the util functions.
