### ISSUE TITLE
face detection container stops running

### ISSUE THREAD

**Issue by cayadehaas** [leolani/cltl-chatbots#6]
The face detection recognition container stops running on its own after which I receive the ConnectionError that I mentioned in another issue before. What can I do to make sure it continues running?

**Comment by tae898** [comment]
Hmm the container shouldn't stop itself. Maybe you don't have enough memory? 

Can you show me your output when you type below in your terminal?

```
free -m
```

```
docker ps -a
```

**Comment by cayadehaas** [comment]
Where should I type this? If I go to Jupyter Lab again and open a terminal there it says free is not a command. When I try the second one this is the output I get
<img width="1073" alt="Schermafbeelding 2021-11-30 om 14 27 50" src="https://user-images.githubusercontent.com/44554850/144055884-fefb2143-dcb3-4cda-8c52-86d251eef9d9.png">
:

**Comment by tae898** [comment]
`free -m` and `docker ps -a` are Unix commands. You type them in your terminal.

**Comment by cayadehaas** [comment]
This free command doesn't work for MacOS, right? Above is the output for `docker ps -a`. Do you have a solution for the container that stops running?

**Comment by tae898** [comment]
I can't say so much at this moment. I have to see the logs of the docker containers to be sure. 
I was asking about the memory, since OOM is the most common cause of docker containers failing.

**Comment by tae898** [comment]
This was solved. On MacOS, you have to ease the hardware constraints (e.g., allocate more memory, cores, etc.)
