### ISSUE TITLE
error while downloading requirements file

### ISSUE THREAD

**Issue by rishvik** [leolani/cltl-chatbots#7]
Running setup.py install for pyaudio ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/rishvikchandel/Desktop/robots/cltl-chatbots-main/venv/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/rk/vbf17nls7k55gznjg1y30kjm0000gn/T/pip-install-xn_jukmv/pyaudio_28cffc523a1f4986a83e7abf0e2c5d82/setup.py'"'"'; __file__='"'"'/private/var/folders/rk/vbf17nls7k55gznjg1y30kjm0000gn/T/pip-install-xn_jukmv/pyaudio_28cffc523a1f4986a83e7abf0e2c5d82/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/rk/vbf17nls7k55gznjg1y30kjm0000gn/T/pip-record-on89b1_1/install-record.txt --single-version-externally-managed --compile --install-headers /Users/rishvikchandel/Desktop/robots/cltl-chatbots-main/venv/include/site/python3.8/pyaudio
         cwd: /private/var/folders/rk/vbf17nls7k55gznjg1y30kjm0000gn/T/pip-install-xn_jukmv/pyaudio_28cffc523a1f4986a83e7abf0e2c5d82/
    Complete output (16 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.9-x86_64-3.8
    copying src/pyaudio.py -> build/lib.macosx-10.9-x86_64-3.8
    running build_ext
    building '_portaudio' extension
    creating build/temp.macosx-10.9-x86_64-3.8
    creating build/temp.macosx-10.9-x86_64-3.8/src
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/rishvikchandel/opt/anaconda3/include -arch x86_64 -I/Users/rishvikchandel/opt/anaconda3/include -arch x86_64 -DMACOSX=1 -I/Users/rishvikchandel/Desktop/robots/cltl-chatbots-main/venv/include -I/Users/rishvikchandel/opt/anaconda3/include/python3.8 -c src/_portaudiomodule.c -o build/temp.macosx-10.9-x86_64-3.8/src/_portaudiomodule.o
    src/_portaudiomodule.c:29:10: fatal error: 'portaudio.h' file not found
    #include "portaudio.h"
             ^~~~~~~~~~~~~
    1 error generated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/rishvikchandel/Desktop/robots/cltl-chatbots-main/venv/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/rk/vbf17nls7k55gznjg1y30kjm0000gn/T/pip-install-xn_jukmv/pyaudio_28cffc523a1f4986a83e7abf0e2c5d82/setup.py'"'"'; __file__='"'"'/private/var/folders/rk/vbf17nls7k55gznjg1y30kjm0000gn/T/pip-install-xn_jukmv/pyaudio_28cffc523a1f4986a83e7abf0e2c5d82/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/rk/vbf17nls7k55gznjg1y30kjm0000gn/T/pip-record-on89b1_1/install-record.txt --single-version-externally-managed --compile --install-headers /Users/rishvikchandel/Desktop/robots/cltl-chatbots-main/venv/include/site/python3.8/pyaudio Check the logs for full command output.

**Comment by piekvossen** [comment]
Pyaudio install problems have been encountered more often with installs where user accounts do not have full rights in local or subdirs.

For chat you do not need audio, in which cas you can exclude it from requirements.txt. Otherwise make sure you have all rights as a user.
