### ISSUE TITLE
Won't let me install requirements

### ISSUE THREAD

**Issue by Pauline-cloud** [leolani/cltl-chatbots#8]
I get this error when trying to install everything. It worked once but once i tried to remove an error, it stopped working completely. 

Collecting cltl.brain
  Using cached cltl.brain-0.0.dev6.tar.gz (253 kB)
  Preparing metadata (setup.py) ... done
  Using cached cltl.brain-0.0.dev5.tar.gz (255 kB)
  Preparing metadata (setup.py) ... done
  Using cached cltl.brain-0.0.dev4.tar.gz (255 kB)
  Preparing metadata (setup.py) ... done
ERROR: Cannot install -r requirements.txt (line 1) because these package versions have conflicting dependencies.

The conflict is caused by:
    cltl-brain 0.0.dev7 depends on iribaker>=0.2
    cltl-brain 0.0.dev6 depends on iribaker>=0.2
    cltl-brain 0.0.dev5 depends on iribaker>=0.2
    cltl-brain 0.0.dev4 depends on iribaker>=0.2

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

**Comment by piekvossen** [comment]
You only need the latest version dev7. Can you try with changing requirements.txt to install dev7?

**Comment by Pauline-cloud** [comment]
I have tried changing the requirements but I'm not sure what you mean by that... I've also tried installing it with pip3 but it won't work, it keeps runnin into errors.

**Comment by Pauline-cloud** [comment]
ERROR: Could not find a version that satisfies the requirement iribaker>=0.2 (from cltl-brain) (from versions: 0.1.1.macosx-10.11-x86_64, 0.1.2.macosx-10.11-x86_64, 0.1.2, 0.1.3, 0.2)
ERROR: No matching distribution found for iribaker>=0.2

**Comment by piekvossen** [comment]
When you reinstall are you doing this in a clean environment? Can you check with pip list to see what versions of cltl brain are installes?

Piek

Verstuurd vanaf mijn iPhone


Op 11 dec. 2021 om 13:03 heeft Pauline-cloud ***@***.***> het volgende geschreven:

﻿

ERROR: Could not find a version that satisfies the requirement iribaker>=0.2 (from cltl-brain) (from versions: 0.1.1.macosx-10.11-x86_64, 0.1.2.macosx-10.11-x86_64, 0.1.2, 0.1.3, 0.2)
ERROR: No matching distribution found for iribaker>=0.2

**Comment by piekvossen** [comment]
It seems as if you install a version over another version. If cltl-brain is alteady installed you should use update.

Piek

Verstuurd vanaf mijn iPhone


Op 11 dec. 2021 om 13:05 heeft Vossen, P.T.J.M. ***@***.***> het volgende geschreven:

﻿ When you reinstall are you doing this in a clean environment? Can you check with pip list to see what versions of cltl brain are installes?

Piek

Verstuurd vanaf mijn iPhone


Op 11 dec. 2021 om 13:03 heeft Pauline-cloud ***@***.***> het volgende geschreven:

﻿

ERROR: Could not find a version that satisfies the requirement iribaker>=0.2 (from cltl-brain) (from versions: 0.1.1.macosx-10.11-x86_64, 0.1.2.macosx-10.11-x86_64, 0.1.2, 0.1.3, 0.2)
ERROR: No matching distribution found for iribaker>=0.2

**Comment by Pauline-cloud** [comment]
Yeah, i've tried makin new environments by doing venv2 and venv3 but the same issues pop up

**Comment by Pauline-cloud** [comment]
pauline@MacBook-Pro-van-Pauline cltl-chatbots % pip list
Package              Version
-------------------- ---------
anyio                3.4.0
appnope              0.1.2
argon2-cffi          21.3.0
argon2-cffi-bindings 21.2.0
attrs                21.2.0
Babel                2.9.1
backcall             0.2.0
bleach               4.1.0
certifi              2021.10.8
cffi                 1.15.0
charset-normalizer   2.0.9
debugpy              1.5.1
decorator            5.1.0
defusedxml           0.7.1
entrypoints          0.3
idna                 3.3
ipykernel            6.6.0
ipython              7.30.1
ipython-genutils     0.2.0
jedi                 0.18.1
Jinja2               3.0.3
json5                0.9.6
jsonschema           4.2.1
jupyter-client       7.1.0
jupyter-core         4.9.1
jupyter-server       1.13.1
jupyterlab           3.2.5
jupyterlab-pygments  0.1.2
jupyterlab-server    2.8.2
MarkupSafe           2.0.1
matplotlib-inline    0.1.3
mistune              0.8.4
nbclassic            0.3.4
nbclient             0.5.9
nbconvert            6.3.0
nbformat             5.1.3
nest-asyncio         1.5.4
notebook             6.4.6
packaging            21.3
pandocfilters        1.5.0
parso                0.8.3
pexpect              4.8.0
pickleshare          0.7.5
pip                  21.3.1
prometheus-client    0.12.0
prompt-toolkit       3.0.24
ptyprocess           0.7.0
pycparser            2.21
Pygments             2.10.0
pyparsing            3.0.6
pyrsistent           0.18.0
python-dateutil      2.8.2
pytz                 2021.3
pyzmq                22.3.0
requests             2.26.0
Send2Trash           1.8.0
setuptools           59.0.1
six                  1.16.0
sniffio              1.2.0
terminado            0.12.1
testpath             0.5.0
tornado              6.1
traitlets            5.1.1
urllib3              1.26.7
wcwidth              0.2.5
webencodings         0.5.1
websocket-client     1.2.3

**Comment by piekvossen** [comment]
What happens if you clone cltl-knowledge representation as a separate project and follow the readme instructions of the brain, so not cltl-chatbots.

Piek

Verstuurd vanaf mijn iPhone


Op 11 dec. 2021 om 13:15 heeft Pauline-cloud ***@***.***> het volgende geschreven:

﻿

Yeah, i've tried makin new environments by doing venv2 and venv3 but the same issues pop up

**Comment by piekvossen** [comment]
Is this from within venv?

Verstuurd vanaf mijn iPhone


Op 11 dec. 2021 om 13:16 heeft Pauline-cloud ***@***.***> het volgende geschreven:

﻿

***@***.*** cltl-chatbots % pip list
Package Version

________________________________

anyio 3.4.0
appnope 0.1.2
argon2-cffi 21.3.0
argon2-cffi-bindings 21.2.0
attrs 21.2.0
Babel 2.9.1
backcall 0.2.0
bleach 4.1.0
certifi 2021.10.8
cffi 1.15.0
charset-normalizer 2.0.9
debugpy 1.5.1
decorator 5.1.0
defusedxml 0.7.1
entrypoints 0.3
idna 3.3
ipykernel 6.6.0
ipython 7.30.1
ipython-genutils 0.2.0
jedi 0.18.1
Jinja2 3.0.3
json5 0.9.6
jsonschema 4.2.1
jupyter-client 7.1.0
jupyter-core 4.9.1
jupyter-server 1.13.1
jupyterlab 3.2.5
jupyterlab-pygments 0.1.2
jupyterlab-server 2.8.2
MarkupSafe 2.0.1
matplotlib-inline 0.1.3
mistune 0.8.4
nbclassic 0.3.4
nbclient 0.5.9
nbconvert 6.3.0
nbformat 5.1.3
nest-asyncio 1.5.4
notebook 6.4.6
packaging 21.3
pandocfilters 1.5.0
parso 0.8.3
pexpect 4.8.0
pickleshare 0.7.5
pip 21.3.1
prometheus-client 0.12.0
prompt-toolkit 3.0.24
ptyprocess 0.7.0
pycparser 2.21
Pygments 2.10.0
pyparsing 3.0.6
pyrsistent 0.18.0
python-dateutil 2.8.2
pytz 2021.3
pyzmq 22.3.0
requests 2.26.0
Send2Trash 1.8.0
setuptools 59.0.1
six 1.16.0
sniffio 1.2.0
terminado 0.12.1
testpath 0.5.0
tornado 6.1
traitlets 5.1.1
urllib3 1.26.7
wcwidth 0.2.5
webencodings 0.5.1
websocket-client 1.2.3

**Comment by Pauline-cloud** [comment]
Yes it is from within venv
i'll try doing the cltl-knowledge

**Comment by Pauline-cloud** [comment]
i've installed everything, made a Graphdb rep with the name sandbox, and tried pip3 install cltl.brain but then this happens

ERROR: Cannot install cltl-brain==0.0.dev4, cltl-brain==0.0.dev5, cltl-brain==0.0.dev6 and cltl-brain==0.0.dev7 because these package versions have conflicting dependencies.

The conflict is caused by:
    cltl-brain 0.0.dev7 depends on iribaker>=0.2
    cltl-brain 0.0.dev6 depends on iribaker>=0.2
    cltl-brain 0.0.dev5 depends on iribaker>=0.2
    cltl-brain 0.0.dev4 depends on iribaker>=0.2

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
(venv) pauline@MacBook-Pro-van-Pauline cltl-knowledgerepresentation %

**Comment by piekvossen** [comment]
This i got from Selene who built cltl-brain:

“ And when installing requirements, I out iribaker on top of the requirements.txt file and it worked”

Can you try that?

Piek

Verstuurd vanaf mijn iPhone


Op 11 dec. 2021 om 13:50 heeft Pauline-cloud ***@***.***> het volgende geschreven:

﻿

i've installed everything, made a Graphdb rep with the name sandbox, and tried pip3 install cltl.brain but then this happens

ERROR: Cannot install cltl-brain==0.0.dev4, cltl-brain==0.0.dev5, cltl-brain==0.0.dev6 and cltl-brain==0.0.dev7 because these package versions have conflicting dependencies.

The conflict is caused by:
cltl-brain 0.0.dev7 depends on iribaker>=0.2
cltl-brain 0.0.dev6 depends on iribaker>=0.2
cltl-brain 0.0.dev5 depends on iribaker>=0.2
cltl-brain 0.0.dev4 depends on iribaker>=0.2

To fix this you could try to:

  1.  loosen the range of package versions you've specified
  2.  remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
(venv) ***@***.*** cltl-knowledgerepresentation %

**Comment by Pauline-cloud** [comment]
What do you mean by 'out'? The requirements file only contains a dot.

**Comment by Pauline-cloud** [comment]
When outing iribaker it downloads and successfully installs, but i am not sure what the next step should be..

**Comment by piekvossen** [comment]
What are you installing precisely? Cltl-chatbots has detailed instructions what to do. Are you following these?

Piek

On 11 Dec 2021, at 15:30, Pauline-cloud ***@***.******@***.***>> wrote:



When outing iribaker it downloads and successfully installs, but i am not sure what the next step should be..

**Comment by Pauline-cloud** [comment]
I've followed the instructions for the cltl-knowledgerepresentation through to the end, with iribaker in the requirements.txt and that successfully installed (this page https://github.com/leolani/cltl-knowledgerepresentation/blob/main/README.md with the instructions), but then i'm not sure what to do next. I also tried to add iribaker at the top of the requirements.txt from clil-chatbots but then i get this error: 
ERROR: Cannot install -r requirements.txt (line 2) and iribaker because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested iribaker
    cltl-brain 0.0.dev7 depends on iribaker>=0.2

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
(venv) pauline@MacBook-Pro-van-Pauline cltl-chatbots %

**Comment by Pauline-cloud** [comment]
I assume they need a newer version of the iribaker, and i've tried installing iribaker seperately, but installing iribaker 0.2 is not functioning it says that there is no matching distribution

**Comment by piekvossen** [comment]
How do you add it to the requirements? With an explicit version constraint or just like that?

Piek

On 11 Dec 2021, at 15:45, Pauline-cloud ***@***.******@***.***>> wrote:



I've followed the instructions for the cltl-knowledgerepresentation through to the end, with iribaker in the requirements.txt and that successfully installed (this page https://github.com/leolani/cltl-knowledgerepresentation/blob/main/README.md with the instructions), but then i'm not sure what to do next. I also tried to add iribaker at the top of the requirements.txt from clil-chatbots but then i get this error:
ERROR: Cannot install -r requirements.txt (line 2) and iribaker because these package versions have conflicting dependencies.

The conflict is caused by:
The user requested iribaker
cltl-brain 0.0.dev7 depends on iribaker>=0.2

To fix this you could try to:

  1.  loosen the range of package versions you've specified
  2.  remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
(venv) ***@***.*** cltl-chatbots %

**Comment by Pauline-cloud** [comment]
I add it like
iribaker

because if i put it like iribaker==0.2, iribaker2, iribaker=0.2 or any other combination it simply states the same error
ERROR: No matching distribution found for iribaker==0.2

**Comment by piekvossen** [comment]
And leaving it out the requirements does not help either?

On 11 Dec 2021, at 15:56, Pauline-cloud ***@***.******@***.***>> wrote:



I add it like
iribaker

because if i put it like iribaker==0.2, iribaker2, iribaker=0.2 or any other combination it simply states the same error
ERROR: No matching distribution found for iribaker==0.2

**Comment by Pauline-cloud** [comment]
no because then we run back to this error again:
ERROR: Could not find a version that satisfies the requirement iribaker>=0.2 (from cltl-brain) (from versions: 0.1.1.macosx-10.11-x86_64, 0.1.2.macosx-10.11-x86_64, 0.1.2, 0.1.3, 0.2)
ERROR: No matching distribution found for iribaker>=0.2

**Comment by piekvossen** [comment]
Can we zoom and you share your screen?

Piek Vossen is inviting you to a scheduled Zoom meeting.

Topic: Combots Lecture
Time: This is a recurring meeting Meet anytime

Join Zoom Meeting
https://vu-live.zoom.us/j/99158476452?pwd=VGVTLy9SRGtEY2FZTDh0L25ZcUF6QT09

Meeting ID: 991 5847 6452
Passcode: 653080


On 11 Dec 2021, at 15:59, Pauline-cloud ***@***.******@***.***>> wrote:



no because then we run back to this error again:
ERROR: Could not find a version that satisfies the requirement iribaker>=0.2 (from cltl-brain) (from versions: 0.1.1.macosx-10.11-x86_64, 0.1.2.macosx-10.11-x86_64, 0.1.2, 0.1.3, 0.2)
ERROR: No matching distribution found for iribaker>=0.2

**Comment by Pauline-cloud** [comment]
(venv2) pauline@MacBook-Pro-van-Pauline cltl-chatbots % pip install iribaker==0.2
Collecting iribaker==0.2
  Using cached iribaker-0.2.tar.gz (2.3 kB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/pauline/cltl-chatbots/venv2/bin/python3.9 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/kb/ft284ty931v48ykk5_gk52p80000gn/T/pip-install-watvnoq8/iribaker_538f81b97a15456ab2440cb24354c731/setup.py'"'"'; __file__='"'"'/private/var/folders/kb/ft284ty931v48ykk5_gk52p80000gn/T/pip-install-watvnoq8/iribaker_538f81b97a15456ab2440cb24354c731/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/kb/ft284ty931v48ykk5_gk52p80000gn/T/pip-pip-egg-info-28xya9nf
       cwd: /private/var/folders/kb/ft284ty931v48ykk5_gk52p80000gn/T/pip-install-watvnoq8/iribaker_538f81b97a15456ab2440cb24354c731/
  Complete output (26 lines):
  running egg_info
  creating /private/var/folders/kb/ft284ty931v48ykk5_gk52p80000gn/T/pip-pip-egg-info-28xya9nf/iribaker.egg-info
  writing /private/var/folders/kb/ft284ty931v48ykk5_gk52p80000gn/T/pip-pip-egg-info-28xya9nf/iribaker.egg-info/PKG-INFO
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/kb/ft284ty931v48ykk5_gk52p80000gn/T/pip-install-watvnoq8/iribaker_538f81b97a15456ab2440cb24354c731/setup.py", line 3, in <module>
      setup(name='iribaker',
    File "/Users/pauline/cltl-chatbots/venv2/lib/python3.9/site-packages/setuptools/__init__.py", line 159, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/Users/pauline/cltl-chatbots/venv2/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 292, in run
      writer(self, ep.name, os.path.join(self.egg_info, ep.name))
    File "/Users/pauline/cltl-chatbots/venv2/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 656, in write_pkg_info
      metadata.write_pkg_info(cmd.egg_info)
    File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 1117, in write_pkg_info
      self.write_pkg_file(pkg_info)
    File "/Users/pauline/cltl-chatbots/venv2/lib/python3.9/site-packages/setuptools/dist.py", line 167, in write_pkg_file
      write_field('Summary', single_line(self.get_description()))
    File "/Users/pauline/cltl-chatbots/venv2/lib/python3.9/site-packages/setuptools/dist.py", line 151, in single_line
      raise ValueError('Newlines are not allowed')
  ValueError: Newlines are not allowed
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/df/50/e5137ce88cb647803e3ad7bb4ee5fb125e29c4277a180319e5949d2ba401/iribaker-0.2.tar.gz#sha256=18ccd1211124fc239f3cb6ed96006417357920f36054d917304d930cc117d8e8 (from https://pypi.org/simple/iribaker/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement iribaker==0.2 (from versions: 0.1.1.macosx-10.11-x86_64, 0.1.2.macosx-10.11-x86_64, 0.1.2, 0.1.3, 0.2)
ERROR: No matching distribution found for iribaker==0.2

**Comment by piekvossen** [comment]
Hoi Pauline,

Kun je dit in de requirements.txt proberen?

cltl.brain==0.0.dev7
cltl.reply-generation==0.0.dev8
cltl.triple-extraction==0.0.dev5
emissor==0.0.dev5
jsonpickle==2.0.0
opencv-python==4.5.4.58
python_on_whales==0.31.0
pillow==8.4.0
spacy==3.2.0
tqdm==4.62.3
ipykernel==6.5.0
matplotlib==3.4.3
matplotlib-inline==0.1.3
seaborn==0.11.2
torch==1.10.0
torchaudio==0.10.0
torchvision==0.11.1


Verstuurd vanaf mijn iPhone


Op 11 dec. 2021 om 16:24 heeft Pauline-cloud ***@***.***> het volgende geschreven:

﻿

(venv2) ***@***.*** cltl-chatbots % pip install iribaker==0.2
Collecting iribaker==0.2
Using cached iribaker-0.2.tar.gz (2.3 kB)
Preparing metadata (setup.py) ... error
ERROR: Command errored out with exit status 1:
command: /Users/pauline/cltl-chatbots/venv2/bin/python3.9 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/kb/ft284ty931v48ykk5_gk52p80000gn/T/pip-install-watvnoq8/iribaker_538f81b97a15456ab2440cb24354c731/setup.py'"'"'; file='"'"'/private/var/folders/kb/ft284ty931v48ykk5_gk52p80000gn/T/pip-install-watvnoq8/iribaker_538f81b97a15456ab2440cb24354c731/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(file) if os.path.exists(file) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/kb/ft284ty931v48ykk5_gk52p80000gn/T/pip-pip-egg-info-28xya9nf
cwd: /private/var/folders/kb/ft284ty931v48ykk5_gk52p80000gn/T/pip-install-watvnoq8/iribaker_538f81b97a15456ab2440cb24354c731/
Complete output (26 lines):
running egg_info
creating /private/var/folders/kb/ft284ty931v48ykk5_gk52p80000gn/T/pip-pip-egg-info-28xya9nf/iribaker.egg-info
writing /private/var/folders/kb/ft284ty931v48ykk5_gk52p80000gn/T/pip-pip-egg-info-28xya9nf/iribaker.egg-info/PKG-INFO
Traceback (most recent call last):
File "", line 1, in
File "/private/var/folders/kb/ft284ty931v48ykk5_gk52p80000gn/T/pip-install-watvnoq8/iribaker_538f81b97a15456ab2440cb24354c731/setup.py", line 3, in
setup(name='iribaker',
File "/Users/pauline/cltl-chatbots/venv2/lib/python3.9/site-packages/setuptools/init.py", line 159, in setup
return distutils.core.setup(**attrs)
File ***@***.***/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py", line 148, in setup
dist.run_commands()
File ***@***.***/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 966, in run_commands
self.run_command(cmd)
File ***@***.***/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
cmd_obj.run()
File "/Users/pauline/cltl-chatbots/venv2/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 292, in run
writer(self, ep.name, os.path.join(self.egg_info, ep.name))
File "/Users/pauline/cltl-chatbots/venv2/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 656, in write_pkg_info
metadata.write_pkg_info(cmd.egg_info)
File ***@***.***/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 1117, in write_pkg_info
self.write_pkg_file(pkg_info)
File "/Users/pauline/cltl-chatbots/venv2/lib/python3.9/site-packages/setuptools/dist.py", line 167, in write_pkg_file
write_field('Summary', single_line(self.get_description()))
File "/Users/pauline/cltl-chatbots/venv2/lib/python3.9/site-packages/setuptools/dist.py", line 151, in single_line
raise ValueError('Newlines are not allowed')
ValueError: Newlines are not allowed

WARNING: Discarding https://files.pythonhosted.org/packages/df/50/e5137ce88cb647803e3ad7bb4ee5fb125e29c4277a180319e5949d2ba401/iribaker-0.2.tar.gz#sha256=18ccd1211124fc239f3cb6ed96006417357920f36054d917304d930cc117d8e8 (from https://pypi.org/simple/iribaker/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement iribaker==0.2 (from versions: 0.1.1.macosx-10.11-x86_64, 0.1.2.macosx-10.11-x86_64, 0.1.2, 0.1.3, 0.2)
ERROR: No matching distribution found for iribaker==0.2

**Comment by Pauline-cloud** [comment]
Helaas hetzelfde probleem weer.
ERROR: Could not find a version that satisfies the requirement iribaker>=0.2 (from cltl-brain) (from versions: 0.1.1.macosx-10.11-x86_64, 0.1.2.macosx-10.11-x86_64, 0.1.2, 0.1.3, 0.2)
ERROR: No matching distribution found for iribaker>=0.2

**Comment by piekvossen** [comment]
Thomas found this:

I think this is this issue:

 https://github.com/pypa/setuptools/issues/2893

Try to up- or downgrade setuptools (I think 58.x and 59.5.0) works

Piek

Verstuurd vanaf mijn iPhone


Op 11 dec. 2021 om 16:47 heeft Pauline-cloud ***@***.***> het volgende geschreven:

﻿

Helaas hetzelfde probleem weer.
ERROR: Could not find a version that satisfies the requirement iribaker>=0.2 (from cltl-brain) (from versions: 0.1.1.macosx-10.11-x86_64, 0.1.2.macosx-10.11-x86_64, 0.1.2, 0.1.3, 0.2)
ERROR: No matching distribution found for iribaker>=0.2
